.PHONY: all build clean

all: build clean

build:
	pdflatex reference.tex
	pdflatex reference.tex
	pdflatex reference.tex

clean:
	rm -f *.aux
	rm -f *.lof
	rm -f *.log
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
